version: "3.9"
services:
  #streamlit:
  #  build: streamlit
  #  ports:
  #    - "8501:8501"
  #  environment:
  #    DB_USER: root
  #    DB_PASS: pass
  #    DB_HOST: db
  #    DB_PORT: 3306
  #    DB_DATABASE: demo
  #
  #    SFTP_HOST: ${SFTP_HOST}
  #    SFTP_USER: ${SFTP_USER}
  #    SFTP_PASS: ${SFTP_PASS}
  #    SFTP_PATH: ${SFTP_PATH}
  #    
  #    VITACOMM_API_KEY: ${VITACOMM_API_KEY}
  #
  #  depends_on: 
  #    db:
  #      condition: service_healthy
  db:
    image: mariadb:10.6.11
    restart: always
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: pass
      MARIADB_DATABASE: demo
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=pass
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55